'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var VueRouter = _interopDefault(require('vue-router'));
var Vue = _interopDefault(require('vue'));
var vueServerRenderer = require('vue-server-renderer');

// @NOTICE This file is generated by sav.

// npm i -D vue vue-router
// 全局的VUE组件需要在这里注册
// 其他需要用Vue的需要从这里引入
Vue.use(VueRouter);

var Article = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "page-article" }, [_c('h2', [_vm._v("Article")]), _vm._v(" "), _c('router-view', { staticClass: "view-container" })], 1);
  },
  staticRenderFns: [],
  name: 'Article',
  getters: [],
  actions: []
};

var ArticlePosts = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-posts" }, [_c('h2', [_vm._v("ArticlePosts")])]);
  }],
  name: 'ArticlePosts',
  getters: [],
  actions: []
};

var ArticleView = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-view" }, [_c('h2', [_vm._v("ArticleView")])]);
  }],
  name: 'ArticleView',
  getters: [],
  actions: []
};

var ArticleModify = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-modify" }, [_c('h2', [_vm._v("ArticleModify")])]);
  }],
  name: 'ArticleModify',
  getters: [],
  actions: []
};

var Home = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "page-home" }, [_c('h2', [_vm._v("客户信息")]), _vm._v(" "), _c('router-view', { staticClass: "view-container" })], 1);
  },
  staticRenderFns: [],
  name: 'Home',
  getters: [],
  actions: []
};

var HomeIndex = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-index" }, [_c('h2', [_vm._v("HomeIndex")]), _vm._v(" "), _c('i', [_vm._v(_vm._s(_vm.name))]), _vm._v(" "), _c('button', { on: { "click": _vm.add } }, [_vm._v("Add")]), _vm._v(" "), _c('router-link', { attrs: { "to": { name: 'HomeAbout' } } }, [_vm._v("About")])], 1);
  },
  staticRenderFns: [],
  name: 'HomeIndex',
  getters: ['a'],
  actions: ['updateA'],
  data() {
    return {
      name: "111111"
    };
  },
  methods: {
    add() {
      console.log(this.getHomeNavMenu);
      this.updateA();
    }
  }
};

var HomeAbout = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-about" }, [_c('h2', [_vm._v("HomeAbout")]), _vm._v(" "), _c('span', [_vm._v(_vm._s(_vm.a) + "-" + _vm._s(_vm.userId) + "-" + _vm._s(_vm.userName))])]);
  },
  staticRenderFns: [],
  name: 'HomeAbout',
  getters: ['a'],
  actions: ['something'],
  payload: [{
    name: 'HomeUserInfo', getters: ['userId']
  }],
  proxys: {
    something({ commit }) {
      commit.updateA({ a: 2, b: 3 });
    }
  },
  data() {
    return {
      userId: 0
    };
  },
  created() {
    setTimeout(() => {
      this.something();
    });
  }
};

var expandRow = {
    render: function () {
        var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', [_c('Row', { staticClass: "expand-row" }, [_c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Job: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v(_vm._s(_vm.row.job))])]), _vm._v(" "), _c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Interest: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v(_vm._s(_vm.row.interest))])]), _vm._v(" "), _c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Birthday: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v(_vm._s(_vm.row.birthday))])])], 1), _vm._v(" "), _c('Row', [_c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Favorite book: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v("《" + _vm._s(_vm.row.book) + "》")])]), _vm._v(" "), _c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Favorite movie: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v(_vm._s(_vm.row.movie))])]), _vm._v(" "), _c('Col', { attrs: { "span": "8" } }, [_c('span', { staticClass: "expand-key" }, [_vm._v("Favorite music: ")]), _vm._v(" "), _c('span', { staticClass: "expand-value" }, [_vm._v(_vm._s(_vm.row.music))])])], 1)], 1);
    },
    staticRenderFns: [],
    props: {
        row: Object
    }
};

var HomeProfile = {
    render: function () {
        var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-profile" }, [_c('Table', { attrs: { "border": "", "columns": _vm.columns10, "data": _vm.data9 } })], 1);
    },
    staticRenderFns: [],
    name: 'HomeProfile',
    components: { expandRow },
    getters: [],
    actions: [],
    data() {
        return {
            columns10: [{
                type: 'expand',
                width: 50,
                render: (h, params) => {
                    return h(expandRow, {
                        props: {
                            row: params.row
                        }
                    });
                },
                sortable: true
            }, {
                title: 'Name',
                key: 'name',
                sortable: true
            }, {
                title: 'Age',
                key: 'age',
                sortable: true
            }, {
                title: 'Address',
                key: 'address',
                sortable: true
            }],
            data9: [{
                name: 'John Brown',
                age: 18,
                address: 'New York No. 1 Lake Park',
                job: 'Data engineer',
                interest: 'badminton',
                birthday: '1991-05-14',
                book: 'Steve Jobs',
                movie: 'The Prestige',
                music: 'I Cry'
            }, {
                name: 'Jim Green',
                age: 25,
                address: 'London No. 1 Lake Park',
                job: 'Data Scientist',
                interest: 'volleyball',
                birthday: '1989-03-18',
                book: 'My Struggle',
                movie: 'Roman Holiday',
                music: 'My Heart Will Go On'
            }, {
                name: 'Joe Black',
                age: 30,
                address: 'Sydney No. 1 Lake Park',
                job: 'Data Product Manager',
                interest: 'tennis',
                birthday: '1992-01-31',
                book: 'Win',
                movie: 'Jobs',
                music: 'Don’t Cry'
            }, {
                name: 'Jon Snow',
                age: 26,
                address: 'Ottawa No. 2 Lake Park',
                job: 'Data Analyst',
                interest: 'snooker',
                birthday: '1988-7-25',
                book: 'A Dream in Red Mansions',
                movie: 'A Chinese Ghost Story',
                music: 'actor'
            }]
        };
    }
};

// @NOTICE This file is generated by sav.

var routes = [{
  component: Article,
  path: "/article",
  children: [{
    component: ArticlePosts,
    name: "ArticlePosts",
    path: "posts"
  }, {
    component: ArticleView,
    name: "ArticleView",
    path: "/articles/:aid"
  }, {
    component: ArticleModify,
    name: "ArticleModify",
    path: "modify/:aid?"
  }, {
    component: ArticleModify,
    name: "ArticleUpdate",
    path: "update/:aid"
  }]
}, {
  component: Home,
  path: "",
  children: [{
    component: HomeIndex,
    name: "HomeIndex",
    path: "/"
  }, {
    component: HomeAbout,
    name: "HomeAbout",
    path: "about"
  }, {
    component: HomeProfile,
    name: "HomeProfile",
    path: "profile/:uid"
  }]
}];

var App = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { attrs: { "id": "app" } }, [_c('router-view', { staticClass: "page-container" })], 1);
  },
  staticRenderFns: [],
  name: 'App',
  getters: [],
  actions: []
};

// @NOTICE This file is generated by sav.

// npm i -D vue-server-renderer
let router = new VueRouter(Object.assign({
  mode: 'history',
  routes,
  linkActiveClass: 'is-active'
}));

let vm = new Vue(Object.assign({
  router
}, App));

var serverEntry = {
  router,
  vm,
  createRenderer: vueServerRenderer.createRenderer,
  renderOptions: {}
};

module.exports = serverEntry;
