// import { promise } from "sav-util";
// import { resolve } from "path";

// @NOTICE This file is generated by sav.

module.exports = class Home {
  async index () {

  }
  async about () {

  }
  async profile () {

  }
  async userInfo () {
    return {
      id: 's1',
      name: 's2'
    }
  }
  async navMenu () {

  }
}
